#spring.application.name=OrderService
spring:
  application:
    name: OrderService
  datasource:
      url: jdbc:h2:mem:order
      driver-class-name: org.h2.Driver
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
    port: 8300

#eureka:
 #   client:
  #    service-url:
   #     defaultZone: http://localhost:8761/eureka/
